---
title: Joey Mason
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header-img: img/home-bg-filtered-1200.jpg
copyright_name: Joey Mason
description: My name is Joey Mason and I'm a software engineer and entrepreneur based in Los Angeles.
baseurl: ''
url: http://www.joeyvmason.com
twitter_username: joeyvmason
github_username: joeyvmason
facebook_app_id: 354876461529088
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
google_tracking_id: UA-79524724-1
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
gems:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
