---
title: Joey Mason
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header-img: img/home-bg.jpg
copyright_name: Joey Mason
description: Joey Mason
baseurl: ''
url: http://joeyvmason.github.io
twitter_username: joeyvmason
github_username: joeyvmason
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude:
- less
- node_modules
- Gruntfile.js
- package.json
- README.md
gems:
- jekyll-paginate
- jekyll-feed
